'use client'
import React, { useEffect, useRef } from 'react'
import {
  useForm,
  Controller,
  FormProvider,
  useFormContext,
} from 'react-hook-form'
import { z } from 'zod'
import { zodResolver } from '@hookform/resolvers/zod'
import { Breadcrumbs, Button } from '@mui/material'
import Box from '@mui/material/Box'
import Typography from '@avc/components/ui/typography'
import FormLabel from '@avc/components/ui/label'
import TextField from '@avc/components/ui/text-field'
import Switch from '@avc/components/ui/switch'
import Card, { CardContent, CardActions } from '@avc/components/ui/card'
import {
  MenuButtonBold,
  MenuButtonItalic,
  MenuControlsContainer,
  MenuDivider,
  MenuSelectHeading,
  RichTextEditor,
  type RichTextEditorRef,
} from 'mui-tiptap'
import StarterKit from '@tiptap/starter-kit'
import AssetPickerDialog from '@avc/features/assets/components/asset-picker-dialog'
import { useMutation } from '@avc/lib/hooks/use-mutation'
import { CREATE_PRODUCT } from '@avc/graphql/mutations'
import { useSnackbar } from '@avc/context/snackbar-context'
import FacetValuePickerDialog from '../pickers/facet-value-picker-dialog'
import FormLayout from '@avc/components/layout/form-layout'
import { CreateProductInput, Facet } from '@avc/generated/graphql'
import Link from 'next/link'

const createProductSchema = z.object({
  autoGenerated: z.boolean().optional(),
  description: z.string().min(1, 'Açıklama zorunludur'),
  draft: z.boolean().optional(),
  facetValueIds: z.array(z.string()).optional(),
  name: z.string().min(1, 'Ürün adı zorunludur'),
  slug: z.string().min(1, 'Slug zorunludur'),
  assets: z.array(z.any()).optional(),
})

type CreateProductInputForm = z.infer<typeof createProductSchema>

export default function CreateProductForm({ facets }: { facets: Facet[] }) {
  const { snackbar } = useSnackbar()
  const [createProductMutation, { loading: createProductLoading }] =
    useMutation(CREATE_PRODUCT)

  const rteRef = useRef<RichTextEditorRef>(null)
  const formMethods = useForm<Zod.infer<typeof createProductSchema>>({
    resolver: zodResolver(createProductSchema),
    defaultValues: {
      autoGenerated: false,
      draft: false,
      description: '',
      name: '',
      slug: '',
      facetValueIds: [],
      assets: [],
    },
  })

  const { control, handleSubmit, formState } = formMethods

  const createProduct = async (data: CreateProductInputForm) => {
    const normalizedData = normalizeProductForm(data)
    const result = await createProductMutation({
      variables: { input: normalizedData },
    })
    return result.data?.createProduct
  }

  const onSubmit = async (data: CreateProductInputForm) => {
    const newProduct = await createProduct(data)

    if (newProduct) {
      snackbar({
        message: 'Ürün başarıyla oluşturuldu',
        variant: 'default',
      })
    } else {
      snackbar({
        message: 'Ürün oluşturulurken bir hata oluştu',
        variant: 'error',
      })
    }
  }

  // **Left Content**: Product Information Form
  const leftContent = (
    <>
      {/* Product Name and Slug Fields */}
      <Box sx={{ display: 'flex', gap: 2, px: 4 }}>
        <Controller
          name="name"
          control={control}
          render={({ field, fieldState: { error } }) => (
            <TextField
              {...field}
              error={!!error}
              helperText={error?.message}
              placeholder="Ürün adı buraya..."
              fullWidth
            />
          )}
        />
        <Controller
          name="slug"
          control={control}
          render={({ field, fieldState: { error } }) => (
            <TextField
              {...field}
              error={!!error}
              helperText={error?.message}
              placeholder="Slug"
              fullWidth
            />
          )}
        />
      </Box>

      <Box sx={{ px: 4 }}>
        <FormLabel sx={{ display: 'block' }}>Ürün Açıklaması</FormLabel>
        <Typography variant="caption" color="textSecondary">
          Bu ürün için kısa bir açıklama yazın
        </Typography>
        <Controller
          name="description"
          control={control}
          render={({ field }) => (
            <RichTextEditor
              ref={rteRef}
              extensions={[StarterKit]}
              content={field.value}
              onUpdate={({ editor }) => {
                field.onChange(editor.getHTML())
              }}
              renderControls={() => (
                <MenuControlsContainer>
                  <MenuSelectHeading />
                  <MenuDivider />
                  <MenuButtonBold />
                  <MenuButtonItalic />
                </MenuControlsContainer>
              )}
              editorProps={{
                attributes: {
                  style: 'height: 200px; overflow-y: auto;',
                },
              }}
            />
          )}
        />
      </Box>
      <Box sx={{ px: 4 }}>
        <Controller
          name="assets"
          control={control}
          render={({ field }) => (
            <AssetPickerDialog
              selectedAssets={field.value || []}
              onAssetsChange={field.onChange}
            />
          )}
        />
      </Box>
    </>
  )

  // **Right Content**: Publish Card
  const rightContent = (
    <PublishCard loading={createProductLoading} facets={facets} />
  )

  const header = (
    <Box
      sx={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
      }}
    >
      <Typography sx={{ px: 4 }} variant="h5" fontWeight="bold">
        Ürün Oluştur
      </Typography>
      <Breadcrumbs sx={{ px: 4 }}>
        <Typography color="text.primary">Katalog</Typography>
        <Link href="/katalog/urunler">
          <Typography color="text.primary">Ürünler</Typography>
        </Link>
        <Typography color="textDisabled">Yeni Ürün Oluştur</Typography>
      </Breadcrumbs>
    </Box>
  )

  return (
    <FormProvider {...formMethods}>
      <form onSubmit={handleSubmit(onSubmit)}>
        <FormLayout
          title={header}
          leftContent={leftContent}
          rightContent={rightContent}
        />
      </form>
    </FormProvider>
  )
}

function PublishCard({
  loading,
  facets,
}: {
  loading: boolean
  facets: Facet[]
}) {
  const {
    control,
    formState: { isDirty },
    watch,
  } = useFormContext<CreateProductInputForm>()

  const isDraft = watch('draft')
  const facetValueIds = watch('facetValueIds')

  useEffect(() => {
    console.log('facetValueIds', facetValueIds)
  }, [facetValueIds])

  return (
    <Card sx={{ p: 0 }}>
      <CardContent sx={{ p: 0 }}>
        <Box
          sx={{
            display: 'flex',
            justifyContent: 'space-between',
            borderBottom: '1px solid',
            borderColor: 'divider',
            p: 2,
          }}
        >
          <Box>
            <Typography variant="h6">Yayınla</Typography>
            <Typography variant="body2">Ürünü şimdi yayınlayın</Typography>
          </Box>
          <Box>
            <Controller
              name="draft"
              control={control}
              render={({ field }) => (
                <Switch
                  {...field}
                  checked={field.value || false}
                  onChange={(e) => field.onChange(e.target.checked)}
                />
              )}
            />
          </Box>
        </Box>
        <Box sx={{ px: 2, pt: 2 }}>
          <Controller
            name="facetValueIds"
            control={control}
            render={({ field }) => (
              <FacetValuePickerDialog
                facets={facets}
                selectedFacetValues={field.value || []}
                onSelectionChange={(selected) =>
                  field.onChange(selected as string[])
                }
              />
            )}
          />
        </Box>
      </CardContent>

      {/* Publish Button */}
      <CardActions
        sx={{
          p: 2,
        }}
      >
        <Button
          disabled={!isDirty || loading}
          variant="contained"
          size="large"
          fullWidth
          type="submit"
        >
          <Typography
            variant="button"
            sx={{ textTransform: 'none' }}
            fontWeight="bold"
          >
            {loading
              ? 'Oluşturuluyor...'
              : isDraft
              ? 'Taslak olarak kaydet'
              : 'Yayınla'}
          </Typography>
        </Button>
      </CardActions>
    </Card>
  )
}

function normalizeProductForm(
  product: Zod.infer<typeof createProductSchema>
): CreateProductInput {
  return {
    name: product.name,
    slug: product.slug,
    description: product.description,
    draft: product.draft,
    facetValueIds: product.facetValueIds,
    featuredAssetId: product.assets?.find((a) => a.featured)?.id,
  }
}
