import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import MainLayout from '@avc/components/layout/main-layout'
import { ThemeProvider } from '@mui/material/styles'
import theme from './theme'
import './globals.css'
import CssBaseline from '@mui/material/CssBaseline'
import Providers from '@avc/providers'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <CssBaseline />
          <MainLayout>{children}</MainLayout>
        </Providers>
      </body>
    </html>
  )
}
