'use client'
import Paper from '@avc/components/ui/paper'
import Box from '@avc/components/ui/box'
import { DataGrid, GridColDef } from '@avc/components/ui/data-grid'
import { turkishLocaleText } from '../../locale/turkish-locale-text'
import TextField from '@avc/components/ui/text-field'
import { Product } from '@avc/generated/graphql'
import Stack from '@avc/components/ui/stack'
import Typography from '@avc/components/ui/typography'
import AddCircleOutlineTwoToneIcon from '@mui/icons-material/AddCircleOutlineTwoTone'
import Button from '@avc/components/ui/button'
import Link from '@avc/components/ui/link'
import SearchTwoToneIcon from '@mui/icons-material/SearchTwoTone'

const columns: GridColDef[] = [
  { field: 'featuredAssetId', headerName: 'Resim', width: 50 },
  {
    field: 'name',
    headerName: 'Ürün Adı',
    width: 250,
    renderCell: (params) => (
      <Box>
        <Link href={`/katalog/urunler/${params.row.slug}`}>
          <Typography variant="body1" sx={{ color: 'secondary.main' }}>
            {params.row.name}
          </Typography>
        </Link>
        <Typography
          variant="caption"
          color="textSecondary"
          sx={{
            display: 'block',
            overflow: 'hidden',
            textOverflow: 'ellipsis',
            whiteSpace: 'nowrap',
          }}
        >
          {(params.row.description || 'Açıklama yok').slice(0, 50) +
            ((params.row.description || '').length > 50 ? '...' : '')}
        </Typography>
      </Box>
    ),
  },
  {
    field: 'slug',
    headerName: 'Slug',
    width: 90,
  },
  {
    field: 'draft',
    headerName: 'Durum',
    sortable: false,
    width: 160,
  },
  {
    field: 'autoGenerated',
    headerName: 'Otomatik Üretildi',
    sortable: false,
    width: 160,
  },
  {
    field: 'facetValues',
    headerName: 'Nitelikler',
    sortable: false,
    width: 160,
  },
]

const paginationModel = { page: 0, pageSize: 5 }

export default function ProductListing({ products }: { products: Product[] }) {
  const rows = products.map((product) => ({
    ...product,
    draft: product.draft ? 'Taslak' : 'Yayında',
    autoGenerated: product.autoGenerated ? 'Evet' : 'Hayır',
    facetValues: product.facetValues
      ?.map((facetValue) => facetValue.name)
      .join(', '),
  }))

  return (
    <Box>
      <Box sx={{ p: 4 }}>
        <Stack direction="row" justifyContent="space-between">
          <Box>
            <Typography variant="h6">Ürünler</Typography>
            <Typography variant="subtitle1" color="textDisabled">
              Mağaza ürünlerinizi listeleyin ve kategorilere ayırın
            </Typography>
          </Box>
          <Box>
            <Link href="/katalog/urunler/yeni">
              <Button
                variant="contained"
                startIcon={<AddCircleOutlineTwoToneIcon />}
              >
                Ürün Ekle
              </Button>
            </Link>
          </Box>
        </Stack>
      </Box>
      <Box sx={{ px: 4, pb: 4 }}>
        <Box sx={{ mb: 2 }}>
          <TextField
            slotProps={{
              input: {
                startAdornment: <SearchTwoToneIcon sx={{ mr: 1 }} />,
              },
            }}
            placeholder="Ürün adına göre filtrele"
            size="small"
          />
        </Box>
        <DataGrid
          localeText={turkishLocaleText}
          columns={columns}
          rows={rows}
          initialState={{ pagination: { paginationModel } }}
          pageSizeOptions={[5, 10]}
          checkboxSelection
          disableRowSelectionOnClick
          sx={{
            borderRadius: 2,
            border: 0,
            '& .MuiDataGrid-columnHeader': { backgroundColor: '#252a2e' },
            '& .MuiDataGrid-filler': { backgroundColor: '#252a2e' },
            '& .MuiDataGrid-row': {
              backgroundColor: 'background.paper',
              '&:hover': {
                backgroundColor: 'action.hover',
              },
            },
            '& .MuiDataGrid-main': {
              borderRadius: 2,
              border: '1px solid #212121',
            },
          }}
        />
      </Box>
    </Box>
  )
}
